version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    ports:
      - "3307:3306"  # Change the host port to 3307
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=mysql+pymysql://root:root@db/school

volumes:
  db_data:
